/**
* Find the Difference
* Given two strings s and t which consist of only lowercase letters.
* String t is generated by random shuffling string s and then add one more letter at a random position.
* Find the letter that was added in t.
* example: s = "abcd" t = "abcde" => 'e'
*
* ASCII Value
* Time complexity:
* Space complexity:
*/

public class Solution {
    /**
     * @param s: a string
     * @param t: a string
     * @return: the letter that was added in t
     */
    public char findTheDifference(String s, String t) {
        // Write your code here

       int sum = 0;
       for (char c: t.toCharArray()) {
           sum = sum + (int) c;
       }

       for (char c: s.toCharArray()) {
           sum = sum - (int) c;
       }

       return (char) sum;
    }
}
